name: "DataObject - Tests"
on:
  push:
    paths:
      - "DataObject/**"
      - ".github/workflows/dataObjectTests.yml"
defaults:
  run:
    working-directory: DataObject
jobs:
  verify-package:
    runs-on: ubuntu-22.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      AWS_REGION: eu-west-2
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          
      - name: Run tests
        run: mvn verify