name: "DataObject - Tests"
on:
  push:
    paths:
      - "DataObject/**"
      - ".github/workflows/dataObjectTests.yaml"
defaults:
  run:
    working-directory: DataObject

env:
  TEST_TAG: dataobject:test

jobs:
  tests:
    runs-on: ubuntu-22.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      AWS_REGION: eu-west-2
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: DataObject/.
          file: DataObject/Dockerfile
          load: true
          target: test
          tags: ${{ env.TEST_TAG }}

      - name: Run tests
        run: |
          docker run --rm ${{ env.TEST_TAG }}