name: "SimpleClient - Integration Tests"
on:
  workflow_call:

concurrency:
  group: client-${{ github.ref }}

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compose up
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.local.yml"
        env:
          AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
          AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
          AWS_REGION: "${AWS_REGION}"
          AWS_BUCKET_NAME: "${AWS_BUCKET_NAME}"
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Run tests
        working-directory: ./SimpleClient
        run: mvn package exec:java